# Generated by Django 4.1.6 on 2023-02-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified time')),
                ('description', models.TextField(verbose_name='Event description')),
                ('name', models.TextField(verbose_name='Event name')),
                ('background', models.TextField(verbose_name='Event background')),
                ('logo', models.TextField(verbose_name='Event logo')),
                ('event_date', models.DateTimeField(verbose_name='Event date and time')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified time')),
                ('name', models.TextField(verbose_name='Organization name')),
                ('description', models.TextField(verbose_name='Organization description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified time')),
                ('email', models.TextField(verbose_name='Customer email')),
                ('phone', models.TextField(verbose_name='Customer phone')),
                ('tickets_count', models.TextField(verbose_name='Ticket count')),
                ('merchant_reply', models.TextField(verbose_name='Merchant reply')),
                ('status', models.TextField(verbose_name='Order status')),
                (
                    'event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='cashapp.event', verbose_name='Event'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified time')),
                ('alias', models.TextField(verbose_name='QR Code alias')),
                ('description', models.TextField(verbose_name='QR Code description')),
                ('price', models.TextField(verbose_name='Event price')),
                (
                    'event',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='cashapp.event', verbose_name='Event'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='cashapp.organization', verbose_name='Organization'
            ),
        ),
    ]
