# Generated by Django 4.1.6 on 2023-02-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cashapp', '0004_alter_order_email_alter_order_merchant_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='background',
            field=models.CharField(
                choices=[
                    ('orchestra', 'orchestra'),
                    ('conference', 'conference'),
                    ('museum', 'museum'),
                    ('party2', 'party2'),
                    ('party1', 'party1'),
                ],
                default=('orchestra', 'orchestra'),
                max_length=255,
                verbose_name='Event background',
            ),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.CharField(
                choices=[('16tonn', '16tonn'), ('ontico', 'ontico'), ('satirikon', 'satirikon'), ('pycon', 'pycon')],
                default=('16tonn', '16tonn'),
                max_length=255,
                verbose_name='Event logo',
            ),
        ),
    ]
