# Generated by Django 4.1.6 on 2023-02-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cashapp', '0005_alter_event_background_alter_event_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Event name'),
        ),
        migrations.AlterField(
            model_name='eventqrcode',
            name='alias',
            field=models.CharField(max_length=100, unique=True, verbose_name='QR Code alias'),
        ),
        migrations.AlterField(
            model_name='eventqrcode',
            name='price',
            field=models.CharField(max_length=30, verbose_name='Event price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Customer email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Customer phone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='qr_id',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='QR ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='qr_status',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='QR Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='qr_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='QR URL'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Order status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tickets_count',
            field=models.CharField(max_length=5, verbose_name='Ticket count'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='merchant_id',
            field=models.CharField(default='', max_length=50, verbose_name='Merchant id'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Organization name'),
        ),
    ]
