# Generated by Django 4.1.6 on 2023-02-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cashapp', '0006_alter_event_name_alter_eventqrcode_alias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qr_status',
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.TextField(blank=True, default='', verbose_name='Customer email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.TextField(blank=True, default='', verbose_name='Customer phone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='qr_id',
            field=models.TextField(blank=True, default='', verbose_name='QR ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='qr_url',
            field=models.TextField(blank=True, default='', verbose_name='QR URL'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, 'Success'), (2, 'Declined'), (3, 'No info'), (3, 'In progress')],
                default=3,
                verbose_name='QR Status',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='tickets_count',
            field=models.TextField(verbose_name='Ticket count'),
        ),
    ]
