# Generated by Django 4.1.6 on 2023-02-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cashapp', '0007_remove_order_qr_status_alter_order_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Customer email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Customer phone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='qr_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='QR ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='qr_url',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='QR URL'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tickets_count',
            field=models.CharField(max_length=10, verbose_name='Ticket count'),
        ),
    ]
