"""
Django settings for my_project project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

from envparse import env as envparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v_44o1ikx2_r%jv-kfqg92mocmnmi)i*wbbf=5!kx$!*^*_0zd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cashapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

APP_URL_BASE: str = envparse('APP_URL', 'https://self-service-checkout-events.5723.raiff2023.codenrock.com').rstrip("/")
REDIRECT_URL: str = envparse('PAYMENT_REDIRECT_URL', 'order', cast=str).strip('/')
QR_GENERATION_URL: str = envparse('RAIFFEISEN_QR_CODE_URL', 'https://pay-test.raif.ru/api/sbp/v2/qrs').rstrip("/")


# Webhook and ivr emulation settings
BACK_SELF_URL: str = 'http://back:' + envparse('NV_CHB_BACK_APP_PORT', '9991')
FRONT_SERVICE_ADDR: str = f'http://front:{envparse("NV_CHB_FRONT_APP_PORT", "9991")}'
WEBHOOK_API_URL_TPL: str = envparse(
    'NV_CHB_BACK_WEBHOOK_API_URL_TPL', FRONT_SERVICE_ADDR + '/api/ext/webimautofaq/{}/questionsAsync'
)
WEBHOOK_SYNC_CACHE_KEY_TPL: str = 'chat-with-webhook-{}'
WEBHOOK_CACHE_EXPIRE_TTL: int = 86400
IVR_API_URL_TPL: str = envparse('NV_CHB_BACK_IVR_API_URL_TPL', FRONT_SERVICE_ADDR + '/api/ext/ivr/{}/question/')
IVR_VERSION_HEADER: str = envparse('NV_CHB_BACK_IVR_VERSION_HEADER', 'application/vnd.nonvoice+json;version=2.0')
OUTGOING_API_URL_TPL: str = envparse(
    'NV_CHB_BACK_IVR_API_URL_TPL', FRONT_SERVICE_ADDR + '/api/ext/outgoing-pi/{}/question/'
)
OUTGOING_VERSION_HEADER: str = envparse(
    'NV_CHB_BACK_OUTGOING_VERSION_HEADER', 'application/vnd.nonvoice+json;version=1.0'
)
REPORT_CACHE_EXPIRE_TIME: int = envparse('NV_CHB_BACK_REPORT_CACHE_EXPIRE_TIME', cast=int, default=60 * 15)
REPORTER_TABLE_NAME: str = envparse('NV_CHB_SUGGEST_REPORTER_TABLE_NAME', default='suggest_reports', cast=str)

# Platform skills endpoint access settings
PLATFORM_API_DOMAIN: str = envparse('NV_CHB_BACK_PLATFORM_API_DOMAIN', 'https://r-chat-prev.raiffeisen.ru/').rstrip("/")
PLATFORM_API_SKILLS_PATH: str = envparse('NV_CHB_BACK_PLATFORM_API_SKILLS_PATH', '/bot/channels/skills/').strip("/")
PLATFORM_API_BOT_TOKEN: str = envparse('NV_CHB_BACK_PLATFORM_API_BOT_TOKEN', 'prev-bot-secret-token')
REQUESTS_CA_BUNDLE: str = envparse('REQUESTS_CA_BUNDLE', 'path/to/certfile')
